# DETECTABLE BLOCK CONFIGURATION FILE
# You can add or remove items from this list as long as the format is adhered to.

non-detectable-blocks:
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_SAPLING
  - ACACIA_WOOD
  - AIR
  - ALLIUM
  - AMETHYST_BLOCK
  - AMETHYST_CLUSTER
  - AMETHYST_SHARD
  - ANCIENT_DEBRIS
  - ANDESITE
  - AZALEA
  - AZALEA_LEAVES
  - AZURE_BLUET
  - BAMBOO
  - BAMBOO_SAPLING
  - BARRIER
  - BASALT
  - BEDROCK
  - BEE_NEST
  - BEEHIVE
  - BEETROOTS
  - BIG_DRIPLEAF
  - BIG_DRIPLEAF_STEM
  - BIRCH_LEAVES
  - BIRCH_PLANKS
  - BIRCH_SAPLING
  - BIRCH_WOOD
  - BLACKSTONE
  - BLUE_ICE
  - BLUE_ORCHID
  - BONE_BLOCK
  - BRAIN_CORAL
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BRAIN_CORAL_WALL_FAN
  - BRICKS
  - BROWN_MUSHROOM
  - BROWN_MUSHROOM_BLOCK
#I do not think that BUBBLE_COLUMN would work, but have added it anyway in case it causes bugs.
  - BUBBLE_COLUMN
  - BUBBLE_CORAL
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - BUBBLE_CORAL_WALL_FAN
  - BUDDING_AMETHYST
  - CACTUS
  - CALCITE
  - CAMPFIRE
  - CARVED_PUMPKIN
#Another odd one which has been included because it may cause bugs.
  - CAVE_AIR
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - CHAIN_COMMAND_BLOCK
  - CHORUS_FLOWER
  - CHORUS_PLANT
  - CLAY
  - COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLESTONE
  - COBWEB
  - COCOA_BEANS
  - COMMAND_BLOCK
  - CONDUIT
  - COPPER_ORE
  - CORNFLOWER
  - CRACKED_DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_TILES
  - CRACKED_NETHER_BRICKS
  - CRACKED_POLISHED_BLACKSTONE_BRICKS
  - CRACKED_STONE_BRICKS
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_PLANKS
  - CRIMSON_ROOTS
  - CRIMSON_STEM
  - CRYING_OBSDIAN
  - CUT_RED_SANDSTONE
  - CUT_SANDSTONE
  - DANDELION
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_SAPLING
  - DARK_OAK_WOOD
  - DARK_PRISMARINE
  - DEAD_BRAIN_CORAL
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BRAIN_CORAL_WALL_FAN
  - DEAD_BUBBLE_CORAL
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_BUBBLE_CORAL_WALL_FAN
  - DEAD_BUSH
  - DEAD_FIRE_CORAL
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_FAN
  - DEAD_FIRE_CORAL_WALL_FAN
  - DEAD_HORN_CORAL
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_HORN_CORAL_FAN
  - DEAD_HORN_CORAL_WALL_FAN
  - DEAD_TUBE_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_TUBE_CORAL_FAN
  - DEAD_TUBE_CORAL_WALL_FAN
  - DEEPSLATE
  - DEEPSLATE_BRICKS
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPLSATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSPLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_TILES
  - DIAMOND_ORE
  - DIORITE
  - DIRT
  - DIRT_PATH
  - DRIED_KELP_BLOCK
  - DRIPSTONE_BLOCK
  - EMERALD_ORE
#Weird tile entity which might cause issues?
  - END_CRYSTAL
  - END_GATEWAY
  - END_PORTAL
  - END_STONE
  - END_STONE_BRICKS
  - FARMLAND
  - FERN
#Making this detectable might allow for some nicer ship damage effects.
  - FIRE
  - FIRE_CORAL
  - FIRE_CORAL_BLOCK
  - FIRE_CORAL_FAN
  - FIRE_CORAL_WALL_FAN
  - FLOWERING_AZALEA
  - FLOWERING_AZALEA_LEAVES
  - FROSTED_ICE
  - GILDED_BLACKSTONE
#How does your ship detection work with tile entities?
  - GLOW_ITEM_FRAME
  - GLOW_LICHEN
  - GRANITE
  - GRASS_BLOCK
  - GRAVEL
  - HANGING_ROOTS
  - HAY_BLOCK
  - HONEYCOMB_BLOCK
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - HORN_CORAL_WALL_ FAN
  - ICE
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_COBBLESTONE
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_DEEPSLATE
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_STONE
  - INFESTED_STONE_BRICKS
  - IRON_ORE
  - JACK_O_LANTERN
  - JIGSAW
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_SAPLING
  - JUNGLE_WOOD
  - KELP_PLANT
  - LAPIS_ORE
  - LARGE_AMETHYST_BUD
  - LARGE_FERN
  - LAVA
  - LIGHT
  - LILAC
  - LILY_OF_THE_VALLEY
  - LILY_PAD
  - MEDIUM_AMETHYST_BUD
#No 'MELON_BLOCK' is in the enum cases list of materials?
  - MELON
  - MELON_STEM
  - MOSSY_COBBLESTONE
  - MOSSY_STONE_BRICKS
  - MOSS_BLOCK
  - MOSS_CARPET
  - MUSHROOM_STEM
  - MYCELIUM
  - NETHERRACK
  - NETHER_BRICKS
  - NETHER_GOLD_ORE
  - NETHER_PORTAL
  - NETHER_QUARTZ_ORE
  - NETHER_SPROUTS
  - NETHER_WART
  - NETHER_WART_BLOCK
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_SAPLING
  - OAK_WOOD
  - OBSIDIAN
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PACKED_ICE
  - PEONY
  - PINK_TULIP
  - PODZOL
  - POINTED_DRIPSTONE
  - POLISHED_ANDESITE
  - POLISHED_BASALT
  - POLISHED_BACKSTONE
  - POLISHED_BLACKSTONE_BRICKS
  - POLISHED_DEEPSLATE
  - POLISHED_DIORITE
  - POLISHED_GRANITE
  - POPPY
  - POTATOES
  - POWDER_SNOW
  - PRISMARINE
  - PRISMARINE_BRICKS
  - PUMPKIN
  - PUMPKIN_STEM
  - PURPUR_BLOCK
  - PURPUR_PILLAR
  - QUARTZ_BLOCK
  - QUARTZ_BRICKS
  - QUARTZ_PILLAR
  - REDSTONE_ORE
  - RED_MUSHROOM
  - RED_MUSHROOM_BLOCK
  - RED_NETHER_BRICKS
  - RED_SAND
  - RED_SANDSTONE
  - RED_TULIP
  - REPEATING_COMMAND_BLOCK
  - ROOTED_DIRT
  - ROSE_BUSH
  - SAND
  - SANDSTONE
  - SEAGRASS
  - SMALL_AMETHYST_BUD
  - SMALL_DRIPLEAF
  - SMOOTH_BASALT
  - SMOOTH_QUARTZ
  - SMOOTH_RED_SANDSTONE
  - SMOOTH_SANDSTONE
  - SMOOTH_STONE
  - SNOW
  - SNOW_BLOCK
  - SOUL_CAMPFIRE
  - SOUL_FIRE
  - SOUL_SAND
  - SOUL_SOIL
  - SPAWNER
  - SPORE_BLOSSOM 
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_SAPLING
  - SPRUCE_WOOD
  - STONE
  - STONE_BRICKS
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_CRIMSON_HYPHAE
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_WARPED_HYPHAE
  - STRIPPED_WARPED_STEM
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TALL_GRASS
  - TALL_SEAGRASS
  - TUBE_CORAL
  - TUBE_CORAL_BLOCK
  - TUBE_CORAL_FAN
  - TUBE_CORAL_WALL_FAN
  - TUFF
  - TURTLE_EGG
  - TWISTING_VINES
  - TWISTING_VINES_PLANT
  - VINE
  - VOID_AIR
  - WARPED_FUNGUS
  - WARPED_HYPHAE
  - WARPED_NYLIUM
  - WARPED_PLANKS
  - WARPED_ROOTS
  - WARPED_STEM
  - WARPED_WART_BLOCK
  - WATER
  - WEEPING_VINES
  - WEEPING_VINES_PLANT
  - WHEAT
  - WHITE_TULIP
  - WITHER_ROSE
  - 
