non-detectable-blocks:
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_SAPLING
  - ACACIA_WOOD
  - AIR
  - ALLIUM
  - AMETHYST_BLOCK
  - AMETHYST_CLUSTER
  - AMETHYST_SHARD
  - ANCIENT_DEBRIS
  - ANDESITE
  - AZALEA
  - AZALEA_LEAVES
  - AZURE_BLUET
  - BAMBOO
  - BAMBOO_SAPLING
  - BARRIER
  - BASALT
  - BEDROCK
  - BEE_NEST
  - BEEHIVE
  - BEETROOTS
  - BIG_DRIPLEAF
  - BIG_DRIPLEAF_STEM
  - BIRCH_LEAVES
  - BIRCH_PLANKS
  - BIRCH_SAPLING
  - BIRCH_WOOD
  - BLACKSTONE
  - BLUE_ICE
  - BLUE_ORCHID
  - BONE_BLOCK
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BRAIN_CORAL_WALL_FAN
  - BRICKS
  - BROWN_MUSHROOM
  - BROWN_MUSHROOM_BLOCK
#I do not think that BUBBLE_COLUMN would work, but have added it anyway in case it causes bugs.
  - BUBBLE_COLUMN
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - BUBBLE_CORAL_WALL_FAN
  - BUDDING_AMETHYST
  - CACTUS
  - CALCITE
  - CAMPFIRE
  - CARVED_PUMPKIN
#Another odd one which has been included because it may cause bugs.
  - CAVE_AIR
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - CHAIN_COMMAND_BLOCK
  - CHORUS_FLOWER
  - CHORUS_PLANT
  - CLAY
  - COAL_BLOCK
  - COAL_ORE
  - COARSE_DIRT
  - COBBLED_DEEPSLATE
  - COBBLESTONE
  - COBWEB
  - COCOA_BEANS
  - COMMAND_BLOCK
  - CONDUIT
  - COPPER_ORE
  - CORNFLOWER
  - CRACKED_DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_TILES
  - CRACKED_NETHER_BRICKS
  - CRACKED_POLISHED_BLACKSTONE_BRICKS
  - CRACKED_STONE_BRICKS
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_PLANKS
  - CRIMSON_ROOTS
  - CRIMSON_STEM
  - CRYING_OBSDIAN
  - CUT_RED_SANDSTONE
  - CUT_SANDSTONE
  - DANDELION
  - DIRT
