# Config file for Minecraft Starship Plugin
# This config file can be reset by using the command /msp config reset

# Output how long it takes to detect/move a ship
timeOperations: false

# Detection Limit
detectionLimit: 500000

# Custom Blocks
customBlocks:
    interface:
        north: false
        east:  false
        south: false
        west:  false
        up:    false
        down:  false

# These blocks can not be detected at all.
forcedUndetectable:
  - AIR
  - BARRIER
  - BEDROCK
  - CAVE_AIR
  - CHAIN_COMMAND_BLOCK
  - COMMAND_BLOCK
  - END_GATEWAY
  - END_PORTAL
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_COBBLESTONE
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_DEEPSLATE
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_STONE
  - INFESTED_STONE_BRICKS
  - JIGSAW
  - LAVA
  - LIGHT
  - NETHER_PORTAL
  - REPEATING_COMMAND_BLOCK
  - SPAWNER
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - VOID_AIR
  - WATER

# These blocks can not be detected by default, but users can allow their detection when using the interface.
defaultUndetectable:
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_SAPLING
  - ACACIA_WOOD
  - ALLIUM
  - AMETHYST_BLOCK
  - AMETHYST_CLUSTER
  - ANCIENT_DEBRIS
  - ANDESITE
  - AZALEA
  - AZALEA_LEAVES
  - AZURE_BLUET
  - BAMBOO
  - BAMBOO_SAPLING
  - BASALT
  - BEETROOTS
  - BEE_NEST
  - BIG_DRIPLEAF
  - BIG_DRIPLEAF_STEM
  - BIRCH_LEAVES
  - BIRCH_SAPLING
  - BIRCH_WOOD
  - BLACKSTONE
  - BLUE_ICE
  - BLUE_ORCHID
  - BONE_BLOCK
  - BRAIN_CORAL
  - BRAIN_CORAL_BLOCK
  - BRAIN_CORAL_FAN
  - BRAIN_CORAL_WALL_FAN
  - BROWN_MUSHROOM
  - BROWN_MUSHROOM_BLOCK
  - BUBBLE_CORAL
  - BUBBLE_CORAL_BLOCK
  - BUBBLE_CORAL_FAN
  - BUBBLE_CORAL_WALL_FAN
  - BUDDING_AMETHYST
  - CACTUS
  - CALCITE
  - CARVED_PUMPKIN
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - CHORUS_FLOWER
  - CHORUS_PLANT
  - CLAY
  - COAL_ORE
  - COARSE_DIRT
  - COBBLESTONE
  - COBWEB
  - COCOA_BEANS
  - CONDUIT
  - COPPER_ORE
  - CORNFLOWER
  - CRIMSON_FUNGUS
  - CRIMSON_HYPHAE
  - CRIMSON_NYLIUM
  - CRIMSON_ROOTS
  - CRIMSON_STEM
  - DANDELION
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_SAPLING
  - DARK_OAK_WOOD
  - DEAD_BRAIN_CORAL
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BRAIN_CORAL_FAN
  - DEAD_BRAIN_CORAL_WALL_FAN
  - DEAD_BUBBLE_CORAL
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_FAN
  - DEAD_BUBBLE_CORAL_WALL_FAN
  - DEAD_BUSH
  - DEAD_FIRE_CORAL
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_FAN
  - DEAD_FIRE_CORAL_WALL_FAN
  - DEAD_HORN_CORAL
  - DEAD_HORN_CORAL_BLOCK
  - DEAD_HORN_CORAL_FAN
  - DEAD_HORN_CORAL_WALL_FAN
  - DEAD_TUBE_CORAL
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_TUBE_CORAL_FAN
  - DEAD_TUBE_CORAL_WALL_FAN
  - DEEPSLATE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DIAMOND_ORE
  - DIORITE
  - DIRT
  - DRIED_KELP_BLOCK
  - DRIPSTONE_BLOCK
  - EMERALD_ORE
  - END_STONE
  - FARMLAND
  - FERN
  - FIRE_CORAL
  - FIRE_CORAL_BLOCK
  - FIRE_CORAL_FAN
  - FIRE_CORAL_WALL_FAN
  - FLOWERING_AZALEA
  - FLOWERING_AZALEA_LEAVES
  - FROSTED_ICE
  - GILDED_BLACKSTONE
  - GLOW_LICHEN
  - GRANITE
  - GRASS_BLOCK
  - GRAVEL
  - HANGING_ROOTS
  - HORN_CORAL
  - HORN_CORAL_BLOCK
  - HORN_CORAL_FAN
  - HORN_CORAL_WALL_FAN
  - ICE
  - IRON_ORE
  - JACK_O_LANTERN
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_SAPLING
  - JUNGLE_WOOD
  - KELP_PLANT
  - LAPIS_ORE
  - LARGE_AMETHYST_BUD
  - LARGE_FERN
  - LILAC
  - LILY_OF_THE_VALLEY
  - LILY_PAD
  - MEDIUM_AMETHYST_BUD
  - MELON
  - MELON_STEM
  - MOSSY_COBBLESTONE
  - MOSS_BLOCK
  - MOSS_CARPET
  - MUSHROOM_STEM
  - MYCELIUM
  - NETHERRACK
  - NETHER_GOLD_ORE
  - NETHER_QUARTZ_ORE
  - NETHER_SPROUTS
  - NETHER_WART
  - NETHER_WART_BLOCK
  - OAK_LEAVES
  - OAK_LOG
  - OAK_SAPLING
  - OAK_WOOD
  - OBSIDIAN
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PACKED_ICE
  - PEONY
  - PINK_TULIP
  - PODZOL
  - POINTED_DRIPSTONE
  - POPPY
  - POTATOES
  - POWDER_SNOW
  - PRISMARINE
  - PUMPKIN
  - PUMPKIN_STEM
  - REDSTONE_ORE
  - RED_MUSHROOM
  - RED_MUSHROOM_BLOCK
  - RED_SAND
  - RED_SANDSTONE
  - RED_TULIP
  - ROOTED_DIRT
  - ROSE_BUSH
  - SAND
  - SANDSTONE
  - SEAGRASS
  - SMALL_AMETHYST_BUD
  - SMALL_DRIPLEAF
  - SNOW
  - SNOW_BLOCK
  - SOUL_CAMPFIRE
  - SOUL_FIRE
  - SOUL_SAND
  - SOUL_SOIL
  - SPORE_BLOSSOM
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_SAPLING
  - SPRUCE_WOOD
  - STONE
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_CRIMSON_HYPHAE
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_WARPED_HYPHAE
  - STRIPPED_WARPED_STEM
  - SUGAR_CANE
  - SUNFLOWER
  - SWEET_BERRY_BUSH
  - TALL_GRASS
  - TALL_SEAGRASS
  - TUBE_CORAL
  - TUBE_CORAL_BLOCK
  - TUBE_CORAL_FAN
  - TUBE_CORAL_WALL_FAN
  - TUFF
  - TURTLE_EGG
  - TWISTING_VINES
  - TWISTING_VINES_PLANT
  - VINE
  - WARPED_FUNGUS
  - WARPED_HYPHAE
  - WARPED_NYLIUM
  - WARPED_ROOTS
  - WARPED_STEM
  - WARPED_WART_BLOCK
  - WEEPING_VINES
  - WEEPING_VINES_PLANT
  - WHEAT
  - WHITE_TULIP
  - WITHER_ROSE


# The settings for power armor
powerArmor:

  # The lore for the items themselves
  lore: "Modules can be added to a complete set"

  # The recipe for the power armor pieces themselves
  recipe:
    layout:
      - "iii"
      - "iai"
      - "iii"
    items:
      # a is the armor piece
      i: IRON_INGOT

  # How often (in ticks) to check and update power armor module status
  # Small values may cause lag
  updateInterval: 20

  # The maximum module weight a player can have before their modules are disabled
  maxModuleWeight: 4

  # The maximum amount of power that can be stored
  maxPower: 5000

  # The items that can be used to add power to the armor.
  # Format: MATERIAL_NAME: POWER_AMOUNT
  powerItems:
    COAL: 100

  # Modules
  modules:
    "Speed Module": # The module name
      # The item lore
      lore: "Grants Speed 1 when applied"

      # The base material for the item
      material: SUGAR

      # The weight. If the player's total weight is above maxWeight the modules are disabled
      # to prevent them from using all modules at once.
      weight: 2

      recipe:
        layout: # The layout of items in the crafting grid
          - "gfg"
          - "fsf"
          - "gfg"
        items: # The key; relates letters in the layout to materials
          g: GOLD_INGOT
          s: SUGAR
          f: FLINT

      # The type of module. Either EFFECT or TODO: add more when added in
      # Effect modules apply potion effects, others have hardcoded custom features.
      type: EFFECT

      # effect field, only used with EFFECT type
      effect:
        # The effect to give. See https://shanebeestudios.com/docs/paper/1.9.4/org/bukkit/potion/PotionEffectType.html
        # for a list of valid effects.
        id: SPEED

        # The effect multiplier. O is level 1, 1 is level 2, etc.
        multiplier: 0

        # How often (in ticks) to re-apply the potion. Higher values may cause lag.
        period: 20

        # The bonus duration. Useful for effects such as night vision to avoid flickering
        durationBonus: 0

        # The amount of power to drain every period ticks
        powerDrain: 1


    "Jump Module":
        lore: "Grants Jump Boost 2 when applied"
        material: RABBIT_FOOT
        weight: 2
        recipe:
          layout:
            - "gfg"
            - "frf"
            - "gfg"
          items:
            g: GOLD_INGOT
            r: RABBIT_FOOT
            f: FLINT
        type: EFFECT
        effect:
          id: JUMP
          multiplier: 1
          period: 20
          durationBonus: 0
          powerDrain: 1
